=== StephanStofer/hslu-xml/database/order.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="order">
        <xs:complexType>
            <xs:all>
                <xs:element name="eventname" type="xs:string"/>
                <xs:element name="eventprice" type="xs:decimal"/>
                <xs:element name="person" type="person"/>
                <xs:element name="services" type="service"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="person">
        <xs:all>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="service">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="serviceTitle" type="xs:string"/>
            <xs:element name="servicePrice" type="xs:decimal"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== StephanStofer/hslu-xml/database/order.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../frontend/xslt/order.xsl"?>
<order xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="order.xsd">
    <eventname></eventname>
    <eventprice>2</eventprice>
    <person>
        <firstName></firstName>
        <lastName></lastName>
    </person>
    <services>
        <serviceTitle></serviceTitle>
        <servicePrice></servicePrice>
    </services>
</order>
